apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: salesforce-reports
  labels:
    app: report-service
spec:
  type: ClusterIP
  selector:
    app: report-service
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: report-service-headless
  namespace: salesforce-reports
  labels:
    app: report-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: report-service
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
